import React, { useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import {
  createChatMessageInputSchema,
  createDocumentInputSchema,
  documentChatResponseSchema,
  documentFindingsResponseSchema,
  documentListResponseSchema,
  documentMetaResponseSchema,
  documentSchema,
  documentStatusSchema,
  documentTraceResponseSchema,
  documentTypeSchema,
  seededChatMessages,
  seededDocuments,
  seededFindings,
  seededTraceEvents,
  updateDocumentInputSchema,
  type ChatMessage,
  type CreateDocumentInput,
  type Document,
  type DocumentMetaResponse,
  type DocumentStatus,
  type DocumentType,
  type Finding,
  type TraceEvent,
  type UpdateDocumentInput,
} from '@supership/shared';

type AsyncState = 'idle' | 'loading' | 'ready' | 'error';
type AppView = 'dashboard' | 'documents' | 'editor' | 'parity';
type EditorMode = 'create' | 'edit';

type EditorDraft = {
  type: DocumentType;
  title: string;
  summary: string;
  content: string;
  status: DocumentStatus;
  ownerId: string;
  tags: string;
};

const apiBaseUrl = (globalThis as { __SUPERSHIP_API_BASE_URL__?: string }).__SUPERSHIP_API_BASE_URL__ ?? 'http://localhost:3000';

const defaultEditorDraft: EditorDraft = {
  type: 'wiki',
  title: '',
  summary: '',
  content: '',
  status: 'draft',
  ownerId: 'person-web-shell',
  tags: 'seed, web',
};

function toEditorDraft(document?: Document): EditorDraft {
  if (!document) {
    return defaultEditorDraft;
  }

  return {
    type: document.type,
    title: document.title,
    summary: document.summary,
    content: document.content,
    status: document.status,
    ownerId: document.ownerId,
    tags: document.tags.join(', '),
  };
}

function draftToCreatePayload(draft: EditorDraft): CreateDocumentInput {
  return createDocumentInputSchema.parse({
    type: draft.type,
    title: draft.title.trim(),
    summary: draft.summary.trim(),
    content: draft.content,
    status: draft.status,
    ownerId: draft.ownerId.trim(),
    tags: draft.tags.split(',').map((tag) => tag.trim()).filter(Boolean),
  });
}

function draftToUpdatePayload(draft: EditorDraft): UpdateDocumentInput {
  return updateDocumentInputSchema.parse({
    type: draft.type,
    title: draft.title.trim(),
    summary: draft.summary.trim(),
    content: draft.content,
    status: draft.status,
    ownerId: draft.ownerId.trim(),
    tags: draft.tags.split(',').map((tag) => tag.trim()).filter(Boolean),
  });
}

async function fetchJson<T>(path: string, init?: RequestInit, schema?: { parse: (value: unknown) => T }): Promise<T> {
  const response = await fetch(`${apiBaseUrl}${path}`, {
    headers: {
      'Content-Type': 'application/json',
      ...(init?.headers ?? {}),
    },
    ...init,
  });

  if (!response.ok) {
    throw new Error(`Request failed with status ${response.status}`);
  }

  const json = await response.json();
  return schema ? schema.parse(json) : (json as T);
}

function createSeedPayload(existingDocuments: Document[]): CreateDocumentInput {
  const nextIndex = existingDocuments.length + 1;
  return createDocumentInputSchema.parse({
    type: nextIndex % 2 === 0 ? 'issue' : 'wiki',
    title: `Seeded document ${nextIndex}`,
    summary: `Autogenerated seed document ${nextIndex} for the SuperShip shell.`,
    content: `This document was created from the web shell to exercise the unified document workflow (${nextIndex}).`,
    status: 'draft',
    ownerId: 'person-web-shell',
    tags: ['seed', 'web'],
  });
}

function createLocalDocument(payload: CreateDocumentInput, existingDocuments: Document[]): Document {
  const timestamp = new Date().toISOString();
  return documentSchema.parse({
    id: `local-${existingDocuments.length + 1}`,
    ...payload,
    createdAt: timestamp,
    updatedAt: timestamp,
  });
}

function updateLocalDocument(existing: Document, payload: UpdateDocumentInput): Document {
  return documentSchema.parse({
    ...existing,
    ...payload,
    updatedAt: new Date().toISOString(),
  });
}

function createLocalParityReply(documentId: string, prompt: string, existingMessages: ChatMessage[]): ChatMessage[] {
  const timestamp = new Date().toISOString();
  return [
    {
      id: `local-user-${existingMessages.length + 1}`,
      documentId,
      role: 'user',
      content: prompt,
      createdAt: timestamp,
    },
    {
      id: `local-assistant-${existingMessages.length + 2}`,
      documentId,
      role: 'assistant',
      content: 'Local parity assistant: review open findings, recent trace events, and the current document summary before choosing the next action.',
      createdAt: new Date(Date.now() + 1000).toISOString(),
    },
  ];
}

function MetricCard({ label, value }: { label: string; value: string | number }) {
  return (
    <div style={{ padding: 12, border: '1px solid #d1d5db', borderRadius: 12, minWidth: 220, background: '#ffffff' }}>
      <strong>{value}</strong>
      <div>{label}</div>
    </div>
  );
}

function NavigationTab({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: '10px 14px',
        borderRadius: 10,
        border: active ? '1px solid #111827' : '1px solid #d1d5db',
        background: active ? '#111827' : '#ffffff',
        color: active ? '#ffffff' : '#111827',
        cursor: 'pointer',
      }}
    >
      {label}
    </button>
  );
}

function DashboardView({ documents, state, onOpenDocuments, onOpenCreate, onOpenParity }: {
  documents: Document[];
  state: AsyncState;
  onOpenDocuments: () => void;
  onOpenCreate: () => void;
  onOpenParity: () => void;
}) {
  const byType = documents.reduce<Record<string, number>>((accumulator, document) => {
    accumulator[document.type] = (accumulator[document.type] ?? 0) + 1;
    return accumulator;
  }, {});

  const activeCount = documents.filter((document) => document.status === 'active').length;
  const draftCount = documents.filter((document) => document.status === 'draft').length;

  return (
    <section>
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 16 }}>
        <MetricCard label="documents visible" value={documents.length} />
        <MetricCard label="active documents" value={activeCount} />
        <MetricCard label="draft documents" value={draftCount} />
        <MetricCard label="workspace state" value={state} />
      </div>

      <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
        <div style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
          <h2 style={{ marginTop: 0 }}>Portfolio mix</h2>
          <ul style={{ margin: 0, paddingLeft: 18 }}>
            {Object.entries(byType).map(([type, count]) => (
              <li key={type}>{type}: {count}</li>
            ))}
          </ul>
        </div>

        <div style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
          <h2 style={{ marginTop: 0 }}>Focused actions</h2>
          <p>The core frontend now supports a routed shell, filtered document explorer, parity console, and document editor.</p>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            <button onClick={onOpenDocuments} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #111827', background: '#111827', color: '#ffffff' }}>
              Explore documents
            </button>
            <button onClick={onOpenCreate} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #d1d5db', background: '#ffffff', color: '#111827' }}>
              Draft a document
            </button>
            <button onClick={onOpenParity} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #d1d5db', background: '#ffffff', color: '#111827' }}>
              Open parity console
            </button>
          </div>
        </div>
      </section>
    </section>
  );
}

function DocumentsView({
  filteredDocuments,
  selectedDocument,
  selectedType,
  searchTerm,
  meta,
  onSearch,
  onSelectType,
  onSelectDocument,
  onEdit,
}: {
  filteredDocuments: Document[];
  selectedDocument?: Document;
  selectedType: 'all' | DocumentType;
  searchTerm: string;
  meta: DocumentMetaResponse;
  onSearch: (value: string) => void;
  onSelectType: (value: 'all' | DocumentType) => void;
  onSelectDocument: (documentId: string) => void;
  onEdit: () => void;
}) {
  return (
    <section>
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 16 }}>
        <input
          aria-label="Search documents"
          value={searchTerm}
          onChange={(event) => onSearch(event.target.value)}
          placeholder="Search by title, summary, or tag"
          style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db', minWidth: 280 }}
        />
        <select
          aria-label="Filter by document type"
          value={selectedType}
          onChange={(event) => onSelectType(event.target.value as 'all' | DocumentType)}
          style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db', minWidth: 220 }}
        >
          <option value="all">All document types</option>
          {meta.documentTypes.map((type) => (
            <option key={type} value={type}>{type}</option>
          ))}
        </select>
      </div>

      <section style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 24, alignItems: 'start' }}>
        <aside style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
          <h2 style={{ marginTop: 0 }}>Document list</h2>
          <p style={{ color: '#6b7280' }}>{filteredDocuments.length} matching documents</p>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'grid', gap: 12 }}>
            {filteredDocuments.map((document) => (
              <li key={document.id}>
                <button
                  onClick={() => onSelectDocument(document.id)}
                  style={{
                    width: '100%',
                    textAlign: 'left',
                    borderRadius: 12,
                    border: document.id === selectedDocument?.id ? '2px solid #2563eb' : '1px solid #d1d5db',
                    background: '#ffffff',
                    padding: 12,
                    cursor: 'pointer',
                  }}
                >
                  <div style={{ fontSize: 12, textTransform: 'uppercase', color: '#6b7280' }}>{document.type}</div>
                  <strong>{document.title}</strong>
                  <div style={{ marginTop: 6, color: '#4b5563' }}>{document.summary}</div>
                </button>
              </li>
            ))}
          </ul>
        </aside>

        <section style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
          {selectedDocument ? (
            <>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 12 }}>
                <span style={{ padding: '4px 8px', borderRadius: 999, background: '#dbeafe', color: '#1d4ed8' }}>{selectedDocument.type}</span>
                <span style={{ padding: '4px 8px', borderRadius: 999, background: '#dcfce7', color: '#166534' }}>{selectedDocument.status}</span>
                <span style={{ padding: '4px 8px', borderRadius: 999, background: '#f3f4f6', color: '#374151' }}>{selectedDocument.ownerId}</span>
              </div>
              <h2 style={{ marginTop: 0 }}>{selectedDocument.title}</h2>
              <p>{selectedDocument.summary}</p>
              <article style={{ whiteSpace: 'pre-wrap', lineHeight: 1.5 }}>{selectedDocument.content}</article>
              <div style={{ marginTop: 16 }}>
                <strong>Tags:</strong> {selectedDocument.tags.join(', ') || 'none'}
              </div>
              <div style={{ marginTop: 16 }}>
                <button onClick={onEdit} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #111827', background: '#111827', color: '#ffffff' }}>
                  Edit selected document
                </button>
              </div>
            </>
          ) : (
            <p>No document selected.</p>
          )}
        </section>
      </section>
    </section>
  );
}

function EditorView({
  draft,
  mode,
  meta,
  activeDocument,
  onChange,
  onSave,
}: {
  draft: EditorDraft;
  mode: EditorMode;
  meta: DocumentMetaResponse;
  activeDocument?: Document;
  onChange: (patch: Partial<EditorDraft>) => void;
  onSave: () => void;
}) {
  return (
    <section style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
      <h2 style={{ marginTop: 0 }}>{mode === 'create' ? 'Create document' : `Edit ${activeDocument?.title ?? 'document'}`}</h2>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
        <label style={{ display: 'grid', gap: 6 }}>
          <span>Title</span>
          <input aria-label="Document title" value={draft.title} onChange={(event) => onChange({ title: event.target.value })} style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db' }} />
        </label>
        <label style={{ display: 'grid', gap: 6 }}>
          <span>Owner</span>
          <input aria-label="Document owner" value={draft.ownerId} onChange={(event) => onChange({ ownerId: event.target.value })} style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db' }} />
        </label>
        <label style={{ display: 'grid', gap: 6 }}>
          <span>Type</span>
          <select aria-label="Document type" value={draft.type} onChange={(event) => onChange({ type: event.target.value as DocumentType })} style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db' }}>
            {meta.documentTypes.map((type) => (
              <option key={type} value={type}>{type}</option>
            ))}
          </select>
        </label>
        <label style={{ display: 'grid', gap: 6 }}>
          <span>Status</span>
          <select aria-label="Document status" value={draft.status} onChange={(event) => onChange({ status: event.target.value as DocumentStatus })} style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db' }}>
            {meta.documentStatuses.map((status) => (
              <option key={status} value={status}>{status}</option>
            ))}
          </select>
        </label>
      </div>

      <label style={{ display: 'grid', gap: 6, marginBottom: 16 }}>
        <span>Summary</span>
        <input aria-label="Document summary" value={draft.summary} onChange={(event) => onChange({ summary: event.target.value })} style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db' }} />
      </label>

      <label style={{ display: 'grid', gap: 6, marginBottom: 16 }}>
        <span>Tags</span>
        <input aria-label="Document tags" value={draft.tags} onChange={(event) => onChange({ tags: event.target.value })} style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db' }} />
      </label>

      <label style={{ display: 'grid', gap: 6, marginBottom: 16 }}>
        <span>Content</span>
        <textarea aria-label="Document content" value={draft.content} onChange={(event) => onChange({ content: event.target.value })} rows={10} style={{ padding: 10, borderRadius: 10, border: '1px solid #d1d5db', resize: 'vertical' }} />
      </label>

      <button onClick={onSave} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #111827', background: '#111827', color: '#ffffff' }}>
        {mode === 'create' ? 'Save new document' : 'Save document changes'}
      </button>
    </section>
  );
}

function ParityView({
  document,
  findings,
  traceEvents,
  chatMessages,
  chatDraft,
  onChatDraftChange,
  onSendChat,
}: {
  document?: Document;
  findings: Finding[];
  traceEvents: TraceEvent[];
  chatMessages: ChatMessage[];
  chatDraft: string;
  onChatDraftChange: (value: string) => void;
  onSendChat: () => void;
}) {
  return (
    <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
      <div style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
        <h2 style={{ marginTop: 0 }}>Parity console</h2>
        <p>Selected document: <strong>{document?.title ?? 'none'}</strong></p>
        <h3>Proactive findings</h3>
        <ul style={{ paddingLeft: 18 }}>
          {findings.map((finding) => (
            <li key={finding.id}>
              <strong>{finding.title}</strong> — {finding.severity} / {finding.status}<br />
              <span>{finding.summary}</span>
            </li>
          ))}
        </ul>
      </div>

      <div style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
        <h3 style={{ marginTop: 0 }}>Trace timeline</h3>
        <ul style={{ paddingLeft: 18 }}>
          {traceEvents.map((event) => (
            <li key={event.id}>
              <strong>{event.kind}</strong> — {event.summary}
            </li>
          ))}
        </ul>
      </div>

      <div style={{ gridColumn: '1 / span 2', border: '1px solid #e5e7eb', borderRadius: 16, padding: 16, background: '#ffffff' }}>
        <h3 style={{ marginTop: 0 }}>On-demand chat</h3>
        <div style={{ display: 'grid', gap: 12, marginBottom: 16 }}>
          {chatMessages.map((message) => (
            <div key={message.id} style={{ padding: 12, borderRadius: 12, background: message.role === 'assistant' ? '#eff6ff' : '#f3f4f6' }}>
              <strong>{message.role}</strong>
              <div>{message.content}</div>
            </div>
          ))}
        </div>
        <textarea
          aria-label="Parity chat prompt"
          value={chatDraft}
          onChange={(event) => onChatDraftChange(event.target.value)}
          rows={4}
          style={{ width: '100%', padding: 10, borderRadius: 10, border: '1px solid #d1d5db', resize: 'vertical', marginBottom: 12 }}
        />
        <button onClick={onSendChat} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #111827', background: '#111827', color: '#ffffff' }}>
          Ask parity assistant
        </button>
      </div>
    </section>
  );
}

export function DocumentApp() {
  const [documents, setDocuments] = useState<Document[]>(seededDocuments);
  const [meta, setMeta] = useState<DocumentMetaResponse>({
    documentTypes: [...documentTypeSchema.options],
    documentStatuses: [...documentStatusSchema.options],
  });
  const [selectedDocumentId, setSelectedDocumentId] = useState<string>(seededDocuments[0]?.id ?? '');
  const [state, setState] = useState<AsyncState>('idle');
  const [message, setMessage] = useState<string>('Loading document workspace...');
  const [view, setView] = useState<AppView>('dashboard');
  const [selectedType, setSelectedType] = useState<'all' | DocumentType>('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [editorMode, setEditorMode] = useState<EditorMode>('create');
  const [draft, setDraft] = useState<EditorDraft>(defaultEditorDraft);
  const [findings, setFindings] = useState<Finding[]>(seededFindings.filter((finding) => finding.documentId === selectedDocumentId));
  const [traceEvents, setTraceEvents] = useState<TraceEvent[]>(seededTraceEvents.filter((event) => event.documentId === selectedDocumentId));
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>(seededChatMessages.filter((message) => message.documentId === selectedDocumentId));
  const [chatDraft, setChatDraft] = useState('What is the next priority here?');

  useEffect(() => {
    async function load() {
      setState('loading');
      try {
        const [documentResponse, metaResponse] = await Promise.all([
          fetchJson('/api/documents', undefined, documentListResponseSchema),
          fetchJson('/api/meta/document-types', undefined, documentMetaResponseSchema),
        ]);

        setDocuments(documentResponse.documents);
        setMeta(metaResponse);
        setSelectedDocumentId((current) => current || documentResponse.documents[0]?.id || '');
        setMessage(`Loaded ${documentResponse.total} documents from the API.`);
        setState('ready');
      } catch {
        setMessage('API unavailable. Rendering bundled seed documents while backend comes online.');
        setState('error');
      }
    }

    void load();
  }, []);

  const filteredDocuments = useMemo(() => {
    const normalizedSearch = searchTerm.trim().toLowerCase();
    return documents.filter((document) => {
      const matchesType = selectedType === 'all' || document.type === selectedType;
      const haystack = `${document.title} ${document.summary} ${document.tags.join(' ')}`.toLowerCase();
      const matchesSearch = normalizedSearch.length === 0 || haystack.includes(normalizedSearch);
      return matchesType && matchesSearch;
    });
  }, [documents, searchTerm, selectedType]);

  const selectedDocument = useMemo(
    () => documents.find((document) => document.id === selectedDocumentId) ?? filteredDocuments[0] ?? documents[0],
    [documents, filteredDocuments, selectedDocumentId],
  );

  useEffect(() => {
    if (selectedDocument && selectedDocument.id !== selectedDocumentId) {
      setSelectedDocumentId(selectedDocument.id);
    }
  }, [selectedDocument, selectedDocumentId]);

  useEffect(() => {
    if (!selectedDocumentId) {
      return;
    }

    async function loadParity() {
      try {
        const [findingsResponse, traceResponse, chatResponse] = await Promise.all([
          fetchJson(`/api/documents/${selectedDocumentId}/findings`, undefined, documentFindingsResponseSchema),
          fetchJson(`/api/documents/${selectedDocumentId}/trace`, undefined, documentTraceResponseSchema),
          fetchJson(`/api/documents/${selectedDocumentId}/chat`, undefined, documentChatResponseSchema),
        ]);

        setFindings(findingsResponse.findings);
        setTraceEvents(traceResponse.events);
        setChatMessages(chatResponse.messages);
      } catch {
        setFindings(seededFindings.filter((finding) => finding.documentId === selectedDocumentId));
        setTraceEvents(seededTraceEvents.filter((event) => event.documentId === selectedDocumentId));
        setChatMessages(seededChatMessages.filter((message) => message.documentId === selectedDocumentId));
      }
    }

    void loadParity();
  }, [selectedDocumentId]);

  function openCreateEditor() {
    setEditorMode('create');
    setDraft(defaultEditorDraft);
    setView('editor');
  }

  function openEditEditor() {
    setEditorMode('edit');
    setDraft(toEditorDraft(selectedDocument));
    setView('editor');
  }

  async function handleCreateSeedDocument() {
    const payload = createSeedPayload(documents);

    try {
      const created = await fetchJson('/api/documents', {
        method: 'POST',
        body: JSON.stringify(payload),
      }, documentSchema);

      setDocuments((current) => [created, ...current]);
      setSelectedDocumentId(created.id);
      setState('ready');
      setMessage(`Created ${created.type} document “${created.title}”.`);
      setView('documents');
    } catch {
      const fallback = createLocalDocument(payload, documents);
      setDocuments((current) => [fallback, ...current]);
      setSelectedDocumentId(fallback.id);
      setState('error');
      setMessage(`API unavailable. Added local fallback document “${fallback.title}”.`);
      setView('documents');
    }
  }

  async function handleSaveDraft() {
    if (editorMode === 'create') {
      const payload = draftToCreatePayload(draft);

      try {
        const created = await fetchJson('/api/documents', {
          method: 'POST',
          body: JSON.stringify(payload),
        }, documentSchema);

        setDocuments((current) => [created, ...current]);
        setSelectedDocumentId(created.id);
        setState('ready');
        setMessage(`Saved new ${created.type} document “${created.title}”.`);
      } catch {
        const fallback = createLocalDocument(payload, documents);
        setDocuments((current) => [fallback, ...current]);
        setSelectedDocumentId(fallback.id);
        setState('error');
        setMessage(`API unavailable. Added local draft document “${fallback.title}”.`);
      }

      setView('documents');
      return;
    }

    if (!selectedDocument) {
      return;
    }

    const payload = draftToUpdatePayload(draft);

    try {
      const updated = await fetchJson(`/api/documents/${selectedDocument.id}`, {
        method: 'PATCH',
        body: JSON.stringify(payload),
      }, documentSchema);

      setDocuments((current) => current.map((document) => document.id === updated.id ? updated : document));
      setSelectedDocumentId(updated.id);
      setState('ready');
      setMessage(`Updated document “${updated.title}”.`);
    } catch {
      const fallback = updateLocalDocument(selectedDocument, payload);
      setDocuments((current) => current.map((document) => document.id === fallback.id ? fallback : document));
      setSelectedDocumentId(fallback.id);
      setState('error');
      setMessage(`API unavailable. Saved local edits for “${fallback.title}”.`);
    }

    setView('documents');
  }

  async function handleSendParityChat() {
    if (!selectedDocument) {
      return;
    }

    const payload = createChatMessageInputSchema.parse({
      documentId: selectedDocument.id,
      content: chatDraft.trim(),
    });

    try {
      const response = await fetchJson(`/api/documents/${selectedDocument.id}/chat`, {
        method: 'POST',
        body: JSON.stringify({ content: payload.content }),
      }, documentChatResponseSchema);

      setChatMessages((current) => [...current, ...response.messages]);
      setMessage(`Parity assistant responded for “${selectedDocument.title}”.`);
      setState('ready');
    } catch {
      const fallback = createLocalParityReply(selectedDocument.id, payload.content, chatMessages);
      setChatMessages((current) => [...current, ...fallback]);
      setMessage(`API unavailable. Added local parity response for “${selectedDocument.title}”.`);
      setState('error');
    }

    setChatDraft('');
  }

  return (
    <main style={{ fontFamily: 'Inter, sans-serif', padding: 24, color: '#111827', background: '#f9fafb', minHeight: '100vh' }}>
      <header style={{ marginBottom: 24 }}>
        <h1 style={{ marginBottom: 8 }}>SuperShip parity workspace</h1>
        <p style={{ margin: 0 }}>Phase 5 adds proactive findings, traceability, and on-demand parity chat on top of the unified document model.</p>
      </header>

      <nav style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 16 }}>
        <NavigationTab label="Dashboard" active={view === 'dashboard'} onClick={() => setView('dashboard')} />
        <NavigationTab label="Documents" active={view === 'documents'} onClick={() => setView('documents')} />
        <NavigationTab label="Editor" active={view === 'editor'} onClick={() => setView('editor')} />
        <NavigationTab label="Parity" active={view === 'parity'} onClick={() => setView('parity')} />
        <button onClick={() => void handleCreateSeedDocument()} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #111827', background: '#111827', color: '#ffffff', marginLeft: 'auto' }}>
          Create seed document
        </button>
      </nav>

      <section style={{ marginBottom: 16 }}>
        <p>{message}</p>
      </section>

      {view === 'dashboard' ? (
        <DashboardView
          documents={documents}
          state={state}
          onOpenDocuments={() => setView('documents')}
          onOpenCreate={openCreateEditor}
          onOpenParity={() => setView('parity')}
        />
      ) : null}

      {view === 'documents' ? (
        <DocumentsView
          filteredDocuments={filteredDocuments}
          selectedDocument={selectedDocument}
          selectedType={selectedType}
          searchTerm={searchTerm}
          meta={meta}
          onSearch={setSearchTerm}
          onSelectType={setSelectedType}
          onSelectDocument={setSelectedDocumentId}
          onEdit={openEditEditor}
        />
      ) : null}

      {view === 'editor' ? (
        <EditorView
          draft={draft}
          mode={editorMode}
          meta={meta}
          activeDocument={selectedDocument}
          onChange={(patch) => setDraft((current) => ({ ...current, ...patch }))}
          onSave={() => void handleSaveDraft()}
        />
      ) : null}

      {view === 'parity' ? (
        <ParityView
          document={selectedDocument}
          findings={findings}
          traceEvents={traceEvents}
          chatMessages={chatMessages}
          chatDraft={chatDraft}
          onChatDraftChange={setChatDraft}
          onSendChat={() => void handleSendParityChat()}
        />
      ) : null}
    </main>
  );
}

if (typeof document !== 'undefined') {
  const rootElement = document.getElementById('root');

  if (rootElement) {
    ReactDOM.createRoot(rootElement).render(
      <React.StrictMode>
        <DocumentApp />
      </React.StrictMode>,
    );
  }
}
