import React, { useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import {
  createDocumentInputSchema,
  documentMetaResponseSchema,
  documentSchema,
  documentListResponseSchema,
  documentTypeSchema,
  seededDocuments,
  type CreateDocumentInput,
  type Document,
  type DocumentMetaResponse,
} from '@supership/shared';

type AsyncState = 'idle' | 'loading' | 'ready' | 'error';

const apiBaseUrl = (globalThis as { __SUPERSHIP_API_BASE_URL__?: string }).__SUPERSHIP_API_BASE_URL__ ?? 'http://localhost:3000';

async function fetchJson<T>(path: string, init?: RequestInit, schema?: { parse: (value: unknown) => T }): Promise<T> {
  const response = await fetch(`${apiBaseUrl}${path}`, {
    headers: {
      'Content-Type': 'application/json',
      ...(init?.headers ?? {}),
    },
    ...init,
  });

  if (!response.ok) {
    throw new Error(`Request failed with status ${response.status}`);
  }

  const json = await response.json();
  return schema ? schema.parse(json) : (json as T);
}

function createSeedPayload(existingDocuments: Document[]): CreateDocumentInput {
  const nextIndex = existingDocuments.length + 1;
  return createDocumentInputSchema.parse({
    type: nextIndex % 2 === 0 ? 'issue' : 'wiki',
    title: `Seeded document ${nextIndex}`,
    summary: `Autogenerated seed document ${nextIndex} for the SuperShip shell.`,
    content: `This document was created from the web shell to exercise the unified document workflow (${nextIndex}).`,
    status: 'draft',
    ownerId: 'person-web-shell',
    tags: ['seed', 'web'],
  });
}

export function DocumentApp() {
  const [documents, setDocuments] = useState<Document[]>(seededDocuments);
  const [meta, setMeta] = useState<DocumentMetaResponse>({
    documentTypes: [...documentTypeSchema.options],
    documentStatuses: ['draft', 'active', 'archived'],
  });
  const [selectedDocumentId, setSelectedDocumentId] = useState<string>(seededDocuments[0]?.id ?? '');
  const [state, setState] = useState<AsyncState>('idle');
  const [message, setMessage] = useState<string>('Loading document workspace...');

  useEffect(() => {
    async function load() {
      setState('loading');
      try {
        const [documentResponse, metaResponse] = await Promise.all([
          fetchJson('/api/documents', undefined, documentListResponseSchema),
          fetchJson('/api/meta/document-types', undefined, documentMetaResponseSchema),
        ]);

        setDocuments(documentResponse.documents);
        setMeta(metaResponse);
        setSelectedDocumentId((current) => current || documentResponse.documents[0]?.id || '');
        setMessage(`Loaded ${documentResponse.total} documents from the API.`);
        setState('ready');
      } catch {
        setMessage('API unavailable. Rendering bundled seed documents while backend comes online.');
        setState('error');
      }
    }

    void load();
  }, []);

  const selectedDocument = useMemo(
    () => documents.find((document) => document.id === selectedDocumentId) ?? documents[0],
    [documents, selectedDocumentId],
  );

  async function handleCreateSeedDocument() {
    const payload = createSeedPayload(documents);

    try {
      const created = await fetchJson('/api/documents', {
        method: 'POST',
        body: JSON.stringify(payload),
      }, documentSchema);

      setDocuments((current) => [created, ...current]);
      setSelectedDocumentId(created.id);
      setState('ready');
      setMessage(`Created ${created.type} document “${created.title}”.`);
    } catch {
      const timestamp = new Date().toISOString();
      const fallback = documentSchema.parse({
        id: `local-${documents.length + 1}`,
        ...payload,
        createdAt: timestamp,
        updatedAt: timestamp,
      });

      setDocuments((current) => [fallback, ...current]);
      setSelectedDocumentId(fallback.id);
      setState('error');
      setMessage(`API unavailable. Added local fallback document “${fallback.title}”.`);
    }
  }

  return (
    <main style={{ fontFamily: 'Inter, sans-serif', padding: 24, color: '#111827' }}>
      <header style={{ marginBottom: 24 }}>
        <h1 style={{ marginBottom: 8 }}>SuperShip document workspace</h1>
        <p style={{ margin: 0 }}>Everything is a document. This shell surfaces the first unified document list and detail view.</p>
      </header>

      <section style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 16 }}>
        <div style={{ padding: 12, border: '1px solid #d1d5db', borderRadius: 12, minWidth: 220 }}>
          <strong>{documents.length}</strong>
          <div>documents visible</div>
        </div>
        <div style={{ padding: 12, border: '1px solid #d1d5db', borderRadius: 12, minWidth: 220 }}>
          <strong>{meta.documentTypes.length}</strong>
          <div>document types modeled</div>
        </div>
        <div style={{ padding: 12, border: '1px solid #d1d5db', borderRadius: 12, minWidth: 220 }}>
          <strong>{state}</strong>
          <div>workspace state</div>
        </div>
      </section>

      <section style={{ marginBottom: 16 }}>
        <button onClick={() => void handleCreateSeedDocument()} style={{ padding: '10px 14px', borderRadius: 10, border: '1px solid #111827', background: '#111827', color: '#ffffff' }}>
          Create seed document
        </button>
        <p style={{ marginTop: 12 }}>{message}</p>
      </section>

      <section style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 24, alignItems: 'start' }}>
        <aside style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16 }}>
          <h2 style={{ marginTop: 0 }}>Document list</h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'grid', gap: 12 }}>
            {documents.map((document) => (
              <li key={document.id}>
                <button
                  onClick={() => setSelectedDocumentId(document.id)}
                  style={{
                    width: '100%',
                    textAlign: 'left',
                    borderRadius: 12,
                    border: document.id === selectedDocument?.id ? '2px solid #2563eb' : '1px solid #d1d5db',
                    background: '#ffffff',
                    padding: 12,
                    cursor: 'pointer',
                  }}
                >
                  <div style={{ fontSize: 12, textTransform: 'uppercase', color: '#6b7280' }}>{document.type}</div>
                  <strong>{document.title}</strong>
                  <div style={{ marginTop: 6, color: '#4b5563' }}>{document.summary}</div>
                </button>
              </li>
            ))}
          </ul>
        </aside>

        <section style={{ border: '1px solid #e5e7eb', borderRadius: 16, padding: 16 }}>
          {selectedDocument ? (
            <>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 12 }}>
                <span style={{ padding: '4px 8px', borderRadius: 999, background: '#dbeafe', color: '#1d4ed8' }}>{selectedDocument.type}</span>
                <span style={{ padding: '4px 8px', borderRadius: 999, background: '#dcfce7', color: '#166534' }}>{selectedDocument.status}</span>
                <span style={{ padding: '4px 8px', borderRadius: 999, background: '#f3f4f6', color: '#374151' }}>{selectedDocument.ownerId}</span>
              </div>
              <h2 style={{ marginTop: 0 }}>{selectedDocument.title}</h2>
              <p>{selectedDocument.summary}</p>
              <article style={{ whiteSpace: 'pre-wrap', lineHeight: 1.5 }}>{selectedDocument.content}</article>
              <div style={{ marginTop: 16 }}>
                <strong>Tags:</strong> {selectedDocument.tags.join(', ') || 'none'}
              </div>
            </>
          ) : (
            <p>No document selected.</p>
          )}
        </section>
      </section>
    </main>
  );
}

if (typeof document !== 'undefined') {
  const rootElement = document.getElementById('root');

  if (rootElement) {
    ReactDOM.createRoot(rootElement).render(
      <React.StrictMode>
        <DocumentApp />
      </React.StrictMode>,
    );
  }
}
