from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

output_path = 'docs/Comparative Analysis.docx'

doc = Document()
style = doc.styles['Normal']
style.font.name = 'Calibri'
style.font.size = Pt(11)

title = doc.add_paragraph()
title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
title_run = title.add_run('Comparative Analysis: Supership vs. Original Fleetgraph App')
title_run.bold = True
title_run.font.size = Pt(16)

subtitle = doc.add_paragraph()
subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
subtitle.add_run('Prepared from the requirements in the “Comparative Analysis” section of docs/shipyard_prd.pdf')

def heading(text):
    doc.add_heading(text, level=1)

def para(text):
    doc.add_paragraph(text)

heading('Executive Summary')
para('Supership is a from-scratch rebuild of the original Ship/Fleetgraph application that preserves the product’s core idea—everything is a document—while intentionally simplifying the implementation into a cleaner pnpm monorepo with shared TypeScript contracts, a Node API, and a React/Vite web client. Overall, the rebuild appears to have gone well as an engineering foundation: the current repository builds successfully, the automated test suite passes, and the app covers the central parity concepts called out in the audit, including the unified document model, document creation and editing flows, dashboard and explorer views, and seeded parity features for findings, traceability, and chat. At the same time, the rebuild is still materially behind the original Fleetgraph product in several high-value areas, especially persistence, collaboration, graph associations, comments/files, auth, and published API contracts. The result is best characterized as a strong parity-oriented prototype and maintainable platform baseline rather than a full feature-equivalent replacement.')

heading('Architectural Comparison')
para('The original Fleetgraph app, as documented in docs/audit/fleetgraph-audit.md, was a broader and more mature system organized around a unified document graph with rich workflows layered on top: wiki pages, issues, programs, projects, week containers, weekly plans, retros, person pages, search, backlinks, comments, files, visibility controls, workspace auth, real-time collaboration, and AI-assisted findings/chat. The audit also highlights that Fleetgraph used “boring, proven technology” intentionally and treated the server as the source of truth while still supporting collaborative editing patterns.')
para('Supership preserves the product philosophy but restructures the implementation into a more explicit three-part monorepo: apps/api, apps/web, and packages/shared. This is a cleaner separation than many organically grown production systems because domain contracts are centralized early in packages/shared and then consumed by both the API and the frontend. That choice is exactly the kind of architectural cleanup an agent or greenfield rebuild tends to make: it optimizes for clarity, traceability, and low-friction iteration rather than preserving historical complexity that accumulated in the original product. A human developer maintaining Fleetgraph incrementally might have kept more compatibility layers or migration-era abstractions; the rebuild instead favors a visibly simpler shape.')
para('The most important structural difference is that Supership currently implements parity behavior with in-memory repositories and seeded data rather than a persistent PostgreSQL-backed document graph. That sharply reduces operational complexity and accelerates delivery, but it also changes the runtime character of the system. The original app’s collaboration model, audit history, and graph-oriented workflows imply a deeper persistence layer and more durable state transitions than Supership currently has. Similarly, proactive findings and chat in Supership are represented as deterministic parity features rather than the richer production-grade AI surfaces described in the Fleetgraph audit. In short, Fleetgraph is architected like an evolved product; Supership is architected like a deliberately clean reconstruction of the product’s core concepts.')

heading('Performance Benchmarks')
para('The current Supership repository provides several measurable signals of engineering health, even though direct apples-to-apples runtime numbers against the original Fleetgraph codebase are not included in this repo. First, the current workspace passes its automated verification suite: 19 tests passed across shared schemas, API routes, and web UI flows (6 in packages/shared, 5 in apps/api, and 8 in apps/web). Second, the workspace production build succeeds across all major packages. Third, the Vite production build for the web app emits a main JavaScript bundle of 219.14 kB raw and 64.26 kB gzip, which is a reasonable size for the current scope of dashboard, explorer, editor, and parity-console functionality.')
para('Repository complexity is also relatively contained. A source scan across tracked TypeScript, JavaScript, TSX, JSX, and Markdown files outside generated folders found 22 relevant files and 2,539 lines. That is small for an application trying to re-establish a document-centric product model, and it supports the claim that Supership is currently a compact, understandable foundation. By contrast, the original Fleetgraph app—based on the audit evidence alone—covered substantially more behavior: real-time collaboration, attachments, comments, visibility controls, richer graph traversal, and extensive automated testing. Even without exact Fleetgraph LOC or bundle metrics in this repository, the functional surface area documented in the audit is clearly broader than what Supership currently ships.')
para('The most meaningful benchmark comparison, then, is not raw speed but scope-to-verification ratio. Supership delivers a coherent, buildable, tested prototype with a relatively small codebase and modest frontend bundle. Fleetgraph delivered a much larger set of production-grade behaviors. Supership therefore wins on present-day simplicity and likely onboarding speed, while Fleetgraph wins on completeness, durability, and functional depth.')

heading('Shortcomings')
para('The clearest shortcomings are documented directly in docs/parity-matrix.md and docs/release-readiness.md. Supership still lists collaboration, associations/graph traversal, comments/files/search index, auth/visibility rules, and OpenAPI publishing as planned rather than done. Persistence is only partial because the current implementation relies on in-memory repositories and seeded data. Release-readiness documentation also explicitly states that there is no persistent database yet, no authentication or authorization, no multi-user collaboration runtime, no durable event log or background processing layer, and no externalized environment configuration strategy. Relative to the original Fleetgraph app, these are not minor omissions; they cut into core production characteristics of the product.')
para('There are also smaller implementation quality signals that show the rebuild is not yet fully polished. The web test run passes, but it emits repeated React testing warnings stating that the current environment is not configured to support act(...). This does not block verification, but it shows that the frontend test harness is still rough around the edges. There is also evidence of duplicate generated test artifacts in the web app (for example, both TypeScript and compiled JavaScript test files appear in the tree), which suggests the rebuild process favored momentum over perfect source hygiene.')
para('The PRD asks for every intervention from the rebuild log, but this repository does not include a dedicated rebuild intervention log artifact. That absence is itself a limitation in relation to the assignment requirements. Without a full intervention ledger, the analysis can identify current gaps and infer likely agent trade-offs, but it cannot enumerate every stuck point with the precision the PRD ideally expects. What the repo does reveal is that the agent-built system converged on the demonstrable subset of parity first and deferred the harder product capabilities—durable persistence, multi-user synchronization, permissions, and richer graph behavior. That pattern reveals a common agent limitation: it succeeds fastest on cleanly specifiable CRUD and UI flows, but it under-delivers on systems that require long-horizon state management, incremental migration realism, and production operational concerns.')

heading('Advances')
para('Supership appears to outperform manual development in speed of establishing a coherent full-stack baseline. In a relatively small codebase, it defines shared contracts, a working API, a functioning frontend shell, seeded parity behaviors, automated tests, build pipelines, and release-verification documentation. That kind of end-to-end scaffolding is exactly where an agent can be faster than a human developer because it can generate repetitive plumbing quickly and keep cross-layer naming reasonably consistent. The monorepo shape is also notably legible: packages/shared, apps/api, and apps/web communicate the architecture immediately, which reduces cognitive load for future contributors.')
para('Another advance is documentation explicitness. The repository includes an audit of the original product, a parity matrix, architecture and release-readiness documentation, and a verification script. Human teams often postpone this kind of comparative and traceability-oriented documentation until late in a project; the Supership rebuild has it as a first-class artifact. That makes the rebuild easier to evaluate, easier to hand off, and easier to extend systematically.')
para('The rebuild also improves separability of concerns. The original Fleetgraph application had to carry the weight of its historical evolution. Supership benefits from hindsight: it starts from the unified document principle but avoids inheriting every incidental complexity of the source system. Even though that simplification leaves functional gaps, it creates a cleaner substrate for the next implementation phase. In that sense, Supership is ahead of the original in architectural readability, even if it is behind in production completeness.')

heading('Trade-off Analysis')
para('Choosing a pnpm monorepo with shared TypeScript contracts was the right call. It directly supports parity work because shared types reduce drift between API and UI expectations. This is especially appropriate for a rebuild whose core risk is semantic mismatch with the original document model. I would keep this decision.')
para('Choosing React plus Vite for the frontend was also the right call. The current production bundle is modest, the build is fast, and the app shell is simple to reason about. For a rebuild, that is a better fit than introducing a heavier framework before parity is stable.')
para('Choosing a Node/Express-style API was reasonable, but stopping at in-memory persistence was only a partially correct call. It was right for speed and proving contracts, but wrong if the goal was closer parity with Fleetgraph’s actual runtime behavior. For a product built around documents, plans, history, and graph relationships, durable storage is not an optional hardening step; it is part of the architecture. This decision was acceptable as a phase boundary but not as a final comparative endpoint.')
para('Representing findings, traceability, and chat as deterministic parity features was a pragmatic trade-off. It allowed the rebuild to demonstrate the shape of those features quickly. However, the trade-off also risks overstating parity because the UI presence of a feature is not the same as the original system’s behavioral depth. I would keep the deterministic scaffolding only as a temporary contract-testing layer and then replace it with persistent, event-backed implementations.')
para('Deferring collaboration, auth, graph associations, and file/comment systems was understandable from a delivery perspective, but these deferrals cut close to the product’s differentiators. A human developer might have reduced surface area elsewhere in order to land at least one of those hard capabilities end to end. The agent instead optimized for broad visible coverage over deep completion in the most complex areas.')

heading('If You Built It Again')
para('If this rebuild were started again, the biggest change should be sequencing: persistence, event history, and graph associations should be established earlier, even if the initial UI is thinner. That would better preserve the original Fleetgraph architecture, where server truth, document relationships, and durable workflows are central rather than optional. Building those foundations first would also make later parity features—comments, audit history, visibility rules, proactive findings, and collaboration—rest on the right substrate instead of seeded stand-ins.')
para('The agent architecture should also preserve a stricter rebuild log. The PRD explicitly values intervention evidence, and that data is necessary to distinguish genuine agent capability from manual rescue. A future run should emit structured step logs, failed attempts, edits, and human interventions as first-class artifacts. That would make the comparative analysis materially stronger and would improve observability beyond the current documentation-only traceability story.')
para('On file editing strategy, I would reduce generated duplication and tighten source hygiene earlier in the process. The presence of both source and compiled artifacts in parts of the tree suggests the rebuild could benefit from stricter output boundaries and cleanup passes after each phase. On context management, I would keep the strong use of audit and parity documents but give the agent a narrower phase-by-phase objective: first data model and persistence, then API parity, then web parity, then collaboration/AI layers, and only then release polish. That ordering would likely produce a system that is less immediately demo-friendly but closer to the original Fleetgraph app where it matters most.')

doc.save(output_path)
print(output_path)
