[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['corepack enable', 'pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm --filter @supership/shared build', 'pnpm --filter @supership/api build']

[start]
cmd = 'pnpm --filter @supership/api start'
